if (isset(newRoom))
  {  set.horizon(34);  prevent.input();  program.control();  load.sound(Sound24);  load.view(View0);  load.view(View73);  load.view(View71);  load.view(View72);  load.view(View73);  load.view(View187);  load.view(View77);  load.view(View69);  load.pic(currentRoom);  draw.pic(currentRoom);  discard.pic(currentRoom);  set.view(ego, View0);  position(ego, 149, 122);  draw(ego);  move.obj(ego, 82, 122, 1, f41);  animate.obj(o1);  position(o1, 152, 109);  set.view(o1, View73);  set.loop(o1, 1);  ignore.objs(o1);  draw(o1);  move.obj(o1, 82, 109, 1, f220);  animate.obj(o2);  position(o2, 38, 91);  set.view(o2, View71);  set.loop(o2, 0);  set.cel(o2, 3);  stop.cycling(o2);  ignore.blocks(o2);  ignore.objs(o2);  draw(o2);  animate.obj(o3);  position(o3, 42, 85);  set.view(o3, View72);  set.loop(o3, 0);  set.cel(o3, 3);  stop.cycling(o3);  draw(o3);  ignore.blocks(o3);  ignore.objs(o3);  animate.obj(o4);  position(o4, 63, 54);  set.view(o4, View187);  set.loop(o4, 0);  set.cel(o4, 0);  stop.cycling(o4);  v36 = 4;  cycle.time(o4, v36);  draw(o4);  stop.update(o4);  animate.obj(o5);  position(o5, 16, 89);  set.view(o5, View187);  set.loop(o5, 2);  fix.loop(o5);  set.cel(o5, 0);  ignore.blocks(o5);  ignore.objs(o5);  draw(o5);  stop.update(o5);  v221 = 2;  set(f221);  show.pic();  return();  }prevent.input();program.control();if (v71 > 0)
  {  print("This is no time for that!");  v71 = 0;  }if (isset(f45))
  {  --v221;  if (v221 == 1)
    {    set(f220);    }  }if (isset(f220))
  {  reset(f220);  ++v220;  if (v220 == 1)
    {    print("You nervously enter the throne room with your sister, Princess "          "Rosella.");    v221 = 3;    }  if (v220 == 2)
    {    print("Before the twin thrones stand your parents, King Graham and Queen "          "Valanice.");    }  if (v220 == 3)
    {    start.cycling(o2);    start.cycling(o3);    start.cycling(o1);    start.cycling(ego);    move.obj(o3, 45, 85, 1, f220);    move.obj(o1, 66, 93, 1, f224);    move.obj(o2, 50, 103, 1, f222);    move.obj(ego, 63, 103, 1, f220);    }  if (v220 == 4)
    {    start.cycling(o3);    move.obj(o3, 53, 93, 1, f223);    }  if (v220 == 5)
    {    start.cycling(o2);    start.cycling(o3);    start.cycling(o1);    start.cycling(ego);    move.obj(o1, 63, 93, 1, f224);    move.obj(o3, 57, 93, 1, f220);    move.obj(o2, 54, 103, 1, f222);    move.obj(ego, 60, 103, 1, f225);    }  if (v220 == 6)
    {    stop.cycling(o3);    print("Graham and Valanice are overjoyed to see you. \"Alexander, where "          "have you been all these years?\" your mother exclaims. Adds your "          "father, \"I'm so proud of both of you!\"");    v221 = 3;    }  if (v220 == 7)
    {    start.cycling(o3);    v36 = 3;    cycle.time(o3, v36);    set.view(o3, View69);    set.loop(o3, 3);    set.cel(o3, 2);    erase(o1);    start.cycling(o2);    v36 = 4;    cycle.time(o2, v36);    set.view(o2, View69);    set.loop(o2, 0);    erase(ego);    v221 = 4;    }  if (v220 == 8)
    {    set.view(o2, View71);    set.view(o3, View72);    set.loop(o3, 0);    stop.cycling(o2);    stop.cycling(o3);    draw(o1);    draw(ego);    start.cycling(o1);    start.cycling(ego);    move.obj(o1, 57, 98, 1, f220);    move.obj(ego, 66, 98, 1, f41);    }  if (v220 == 9)
    {    move.obj(o1, 60, 103, 1, f220);    move.obj(ego, 63, 93, 1, f41);    }  if (v220 == 10)
    {    v36 = 3;    cycle.time(o3, v36);    set.view(o3, View69);    set.loop(o3, 1);    set.cel(o3, 2);    start.cycling(o3);    erase(ego);    v36 = 4;    cycle.time(o2, v36);    set.view(o2, View69);    set.loop(o2, 2);    start.cycling(o2);    erase(o1);    v221 = 4;    }  if (v220 == 11)
    {    stop.update(o2);    stop.update(o3);    set.view(o2, View71);    set.view(o3, View72);    set.loop(o3, 0);    force.update(o2);    force.update(o3);    draw(o1);    draw(ego);    start.cycling(o1);    start.cycling(ego);    move.obj(o1, 57, 98, 1, f220);    move.obj(ego, 66, 98, 1, f41);    print("What a joyous family reunion! You are home at last!");    }  if (v220 == 12)
    {    move.obj(o1, 63, 93, 1, f224);    move.obj(ego, 60, 103, 1, f225);    v221 = 4;    }  if (v220 == 13)
    {    start.cycling(ego);    start.cycling(o1);    move.obj(ego, 82, 122, 1, f220);    move.obj(o1, 82, 109, 1, f224);    }  if (v220 == 14)
    {    move.obj(ego, 87, 122, 1, f220);    }  if (v220 == 15)
    {    set.loop(o1, 1);    set.loop(ego, 1);    stop.update(o2);    stop.update(o1);    stop.update(ego);    force.update(o1);    force.update(ego);    force.update(o2);    print("King Graham points to the mirror. \"That was once a magic mirror, "          "son,\" he says sadly. \"But, it has been clouded ever since the "          "night you disappeared from your cradle.\"");    v221 = 5;    }  if (v220 == 16)
    {    start.update(o4);    start.cycling(o4);    end.of.loop(o4, f220);    }  if (v220 == 17)
    {    v36 = 3;    cycle.time(o4, v36);    start.cycling(o4);    set.loop(o4, 1);    v221 = 6;    }  if (v220 == 18)
    {    print("Before your astonished eyes, the magic mirror clears, and shines "          "anew with brilliant clarity. Queen Valanice cries in delight, \"The "          "terrible dragon is dead, our children are home, and the future looks "          "bright for us all!\"");    v221 = 3;    }  if (v220 == 19)
    {    start.update(o2);    start.cycling(o2);    v36 = 1;    cycle.time(o2, v36);    move.obj(o2, 42, 111, 1, f220);    }  if (v220 == 20)
    {    move.obj(o2, 19, 111, 1, f220);    }  if (v220 == 21)
    {    start.update(o5);    erase(o5);    print("King Graham lovingly retrieves his adventurer's hat with the red "          "feather.");    move.obj(o2, 42, 111, 1, f220);    }  if (v220 == 22)
    {    print("With emotion he tells you, \"Alexander, Rosella, this old hat and I "          "have been through a lot together. Now, it's time he had a new "          "travelling companion.\" He flings it in your direction.");    move.obj(o2, 50, 103, 1, f220);    }  if (v220 == 23)
    {    stop.cycling(o2);    stop.update(o2);    set.cel(o2, 3);    force.update(o2);    position(o5, 55, 81);    draw(o5);    move.obj(o5, 72, 64, 1, f220);    }  if (v220 == 24)
    {    print("Up and up it gently arcs. You raise your arms to catch it, and, so "          "does Princess Rosella! Down it comes, nearer and nearer...");    start.update(o1);    start.update(ego);    set.view(o1, View77);    set.view(ego, View77);    set.loop(o1, 1);    set.loop(ego, 0);    start.cycling(o1);    start.cycling(ego);    set(f35);    move.obj(o5, 82, 73, 1, f220);    }  if (v220 == 25)
    {    stop.cycling(o5);    stop.motion(o5);    stop.cycling(ego);    reset(f35);    stop.cycling(o1);    set.cel(ego, 1);    set.cel(o1, 1);    v221 = 3;    }  if (v220 == 26)
    {    print("The End\n\n");    v221 = 7;    }  if (v220 == 27)
    {    print("Congratulations on your successful completion of \"King's Quest "          "III!!\" We hope you have enjoyed playing as much as we enjoyed "          "creating it for you.");    print("May the adventuring continue with \"King's Quest IV!\"");    }  }if (isset(f222))
  {  reset(f222);  stop.cycling(o2);  }if (isset(f223))
  {  reset(f223);  stop.cycling(o3);  }if (isset(f224))
  {  reset(f224);  stop.cycling(o1);  }if (isset(f225))
  {  reset(f225);  stop.cycling(ego);  }if (isset(f221))
  {  sound(Sound24, f221);  }return();[ Messages#message 1 "You nervously enter the throne room with your sister, Princess Rosella."#message 2 "Before the twin thrones stand your parents, King Graham and Queen Valanice."#message 3 "Graham and Valanice are overjoyed to see you. \"Alexander, where have you been all these years?\" your mother exclaims. Adds your father, \"I'm so proud of both of you!\""#message 4 "What a joyous family reunion! You are home at last!"#message 5 "King Graham points to the mirror. \"That was once a magic mirror, son,\" he says sadly. \"But, it has been clouded ever since the night you disappeared from your cradle.\""#message 6 "Before your astonished eyes, the magic mirror clears, and shines anew with brilliant clarity. Queen Valanice cries in delight, \"The terrible dragon is dead, our children are home, and the future looks bright for us all!\""#message 7 "King Graham lovingly retrieves his adventurer's hat with the red feather."#message 8 "With emotion he tells you, \"Alexander, Rosella, this old hat and I have been through a lot together. Now, it's time he had a new travelling companion.\" He flings it in your direction."#message 9 "Up and up it gently arcs. You raise your arms to catch it, and, so does Princess Rosella! Down it comes, nearer and nearer..."#message 10 "The End\n\n"#message 11 ""#message 12 "Congratulations on your successful completion of \"King's Quest III!!\" We hope you have enjoyed playing as much as we enjoyed creating it for you."#message 13 ""#message 14 "May the adventuring continue with \"King's Quest IV!\""#message 15 ""#message 16 "This is no time for that!"