if (isset(newRoom))
{  load.pic(currentRoom);  draw.pic(currentRoom);  discard.pic(currentRoom);  set.horizon(48);  v56 = 6;  set(f60);  v57 = 99;  v58 = 89;  load.sound(Sound1);  load.view(View0);  load.view(View11);  load.view.v(currentEgoView);  set.view.v(ego, currentEgoView);  if (isset(f48))
  {    if (previousRoom == 69)
    {      position(ego, 73, 55);    }  }  if (isset(f47))
  {    draw(ego);  }  ignore.blocks(ego);  if (isset(f182))
  {    load.logics(Logic119);    call(Logic119);  }  show.pic();  return();}if (isset(f182))
{  call(Logic119);}if (isset(f33))
{  ignore.blocks(ego);}if (!isset(f46) &&  isset(egoHitSpecial) &&  !isset(f221))
{  set(f46);  prevent.input();  set(f221);  ignore.blocks(ego);  get.priority(ego, v36);  set.priority.v(ego, v36);  set.view(ego, View11);  v36 = 4;  cycle.time(ego, v36);  v37 = v40;  v38 = 164;  v36 = 4;  move.obj.v(ego, v37, v38, v36, f220);  sound(Sound1, f238);}if (isset(f220))
{  reset(f220);  erase(ego);  set(f44);  print("The treacherous chasm has claimed another victim.");  reset(f46);  return();}if ((said("examine", "area") ||  said("examine")))
{  print("The countryside of Daventry looks as if it had once been beautiful. "    "But now, trees are charred, a chasm splits the earth, and wildflowers "    "no longer grow. Nearby is an old, broken-down well that someone has "    "filled with rocks. It's useless now.");}if ((said("examine", "brush") ||  said("examine", "forest")))
{  print("Some plants and trees around Daventry have been burnt black and "    "leafless.");}if ((said("examine", "flower") ||  said("capture", "flower")))
{  print("Wildflowers no longer grow here.");}if (said("examine", "deck"))
{  print("There is nothing interesting on the ground but grass.");}if (said("examine", "sky"))
{  print("The sky is blue and the sun is shining, but yet a feeling of sadness "    "lingers here.");}if (said("climb", "forest"))
{  print("There are no good climbing trees that you can see.");}if ((said("examine", "well") ||  said("look in", "well") ||  said("climb", "well")))
{  print("The old well has been filled with rocks. It's useless. Like everything "    "else in Daventry, the well gives a feeling of futileness.");}if ((said("look in", "canyon") ||  said("examine", "canyon") ||  said("examine", "above", "canyon")))
{  print("A deep chasm splits the earth. Possibly, an earthquake ripped through "    "Daventry at one time. Looking across the chasm, you see nothing but "    "more charred countryside.");}if ((said("examine", "cage") ||  said("examine", "above", "cage")))
{  print("A stone wall travels to the north and south. You see if you can climb "    "it, but find it too high. There is nothing of any interest on the "    "other side of the wall, anyway.");}if ((said("climb", "cage") ||  said("climb", "above", "cage") ||  said("jump", "cage") ||  said("jump", "above", "cage")))
{  print("%m9");}if ((said("jump", "above", "canyon") ||  said("climb", "canyon") ||  said("climb", "down", "canyon") ||  said("jump", "down", "canyon") ||  said("board", "above", "canyon") ||  said("jump", "canyon")))
{  print("The chasm is much too wide to jump across, and too treacherous to "    "climb.");}if (edgeEgoHit == TOP_EDGE)
{  new.room(Logic69);}if (edgeEgoHit == RIGHT_EDGE)
{  new.room(Logic61);}return();[Messages#message 1 "The countryside of Daventry looks as if it had once been beautiful. But now, trees are charred, a chasm splits the earth, and wildflowers no longer grow. Nearby is an old, broken-down well that someone has filled with rocks. It's useless now."#message 2 "Some plants and trees around Daventry have been burnt black and leafless."#message 3 "Wildflowers no longer grow here."#message 4 "There is nothing interesting on the ground but grass."#message 5 "The sky is blue and the sun is shining, but yet a feeling of sadness lingers here."#message 6 "There are no good climbing trees that you can see."#message 7 "The old well has been filled with rocks. It's useless. Like everything else in Daventry, the well gives a feeling of futileness."#message 8 "A deep chasm splits the earth. Possibly, an earthquake ripped through Daventry at one time. Looking across the chasm, you see nothing but more charred countryside."#message 9 "A stone wall travels to the north and south. You see if you can climb it, but find it too high. There is nothing of any interest on the other side of the wall, anyway."#message 10 "%m9"#message 11 "The chasm is much too wide to jump across, and too treacherous to climb."#message 12 "The treacherous chasm has claimed another victim."
